import assert from "node:assert/strict";
import test from "node:test";

import {
  insertMatchExplanationSnapshots,
  MATCH_EXPLANATION_SNAPSHOT_DEDUPE_COLUMNS,
} from "@/lib/background-operations";
import type { MatchExplanationSnapshotPayload } from "@/lib/background-explanations";

test("match explanation snapshots ignore duplicate provenance rows", async () => {
  const snapshot: MatchExplanationSnapshotPayload = {
    confidence_band: "Moderate",
    explanation_version: "background-explanation-v1",
    factor_codes: ["cause_overlap"],
    match_id: "00000000-0000-0000-0000-000000000001",
    privacy_note: "Coarse only.",
    profile_id: "00000000-0000-0000-0000-000000000002",
    provenance: "Generated by saved-search-cron.",
    redacted_surfaces: ["Exact wishes"],
    scanned_surfaces: ["Broad registry previews"],
    score_bucket: "60-74",
    source_run_id: "saved-search-1",
    source_run_kind: "saved_search_scan",
    summary: "Moderate confidence from privacy-safe factor codes.",
    workflow_stage: "suggested",
  };
  const calls: Array<{
    rows: MatchExplanationSnapshotPayload[];
    options: { ignoreDuplicates?: boolean; onConflict?: string };
  }> = [];
  const supabase = {
    from(table: string) {
      assert.equal(table, "match_explanation_snapshots");

      return {
        upsert(
          rows: MatchExplanationSnapshotPayload[],
          options: { ignoreDuplicates?: boolean; onConflict?: string },
        ) {
          calls.push({ options, rows });
          return { error: null };
        },
      };
    },
  };

  const error = await insertMatchExplanationSnapshots({
    snapshots: [snapshot],
    supabase: supabase as never,
  });

  assert.equal(error, null);
  assert.equal(calls.length, 1);
  assert.equal(calls[0]?.options.ignoreDuplicates, true);
  assert.equal(calls[0]?.options.onConflict, MATCH_EXPLANATION_SNAPSHOT_DEDUPE_COLUMNS);
  assert.deepEqual(calls[0]?.rows, [snapshot]);
});
