import type { Metadata } from "next";
import Link from "next/link";

import { runInstitutionalAction } from "@/app/institutions/actions";
import styles from "@/app/institutions/institutions.module.css";
import {
  InstitutionalDate,
  InstitutionalDisclosure,
  InstitutionalEmpty,
  InstitutionalKeyValue,
  InstitutionalMetric,
  InstitutionalSectionHeader,
  InstitutionalStatus,
  formatInstitutionalLabel,
  formatInstitutionalMoney,
  institutionalStatusTone,
} from "@/components/institutions/institutional-ui";
import { InstitutionalOrganizationAdministration } from "@/components/institutions/institutional-organization-administration";
import { SiteFooter } from "@/components/layout/site-footer";
import { SiteTopbar } from "@/components/layout/site-topbar";
import { getViewer } from "@/lib/app-data";
import { getFormMessage } from "@/lib/form-state";
import { loadInstitutionalWorkspace } from "@/lib/institutional-data";
import { institutionalOrganizationDealHref } from "@/lib/institutional-trade";
import { getPrimaryNavLinks, getTopbarActions } from "@/lib/site";

export const dynamic = "force-dynamic";
export const revalidate = 0;

interface PageProps { params: Promise<{ organizationId: string }>; searchParams: Promise<Record<string, string | string[] | undefined>>; }

const ORGANIZATION_WORKSPACE_NAV = [
  ["Overview", "#overview"],
  ["Programs and mandates", "#programs"],
  ["Resources", "#resources"],
  ["Opportunities", "#opportunities"],
  ["Matches", "#matches"],
  ["Deal rooms", "#deal-rooms"],
  ["Authority and funds", "#authority-and-funds"],
  ["Team and verification", "#organization-administration"],
  ["Templates and reports", "#templates"],
  ["Integrations", "#integrations"],
] as const;

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { organizationId } = await params;
  try { const data = await loadInstitutionalWorkspace(organizationId); return { title: data.organization.display_name, description: data.organization.summary || "Institutional Moral Trade profile" }; }
  catch { return { title: "Institutional organization" }; }
}

function base(actionType: string, organizationId: string) {
  return <><input name="actionType" type="hidden" value={actionType} /><input name="actingCapacity" type="hidden" value="organization" /><input name="actingOrganizationId" type="hidden" value={organizationId} /><input name="organizationId" type="hidden" value={organizationId} /><input name="returnTo" type="hidden" value={`/institutions/${organizationId}`} /></>;
}

export default async function InstitutionalWorkspacePage({ params, searchParams }: PageProps) {
  const [{ organizationId }, viewer, resolvedSearchParams] = await Promise.all([params, getViewer(), searchParams]);
  const data = await loadInstitutionalWorkspace(organizationId);
  const message = getFormMessage(resolvedSearchParams);
  const isMember = Boolean(viewer && data.memberships.some((membership) => membership.profile_id === viewer.authUser.id && membership.status === "active"));
  const actions = getTopbarActions(Boolean(viewer));
  const programById = new Map(data.programs.map((program) => [program.id, program]));
  const activeGrants = data.authorityGrants.filter((grant) => !grant.revoked_at);

  return <div className={styles.shell}>
    <SiteTopbar brandHref="/" links={getPrimaryNavLinks(Boolean(viewer))} authLink={actions.authLink} primaryAction={actions.primaryAction} showLogout={Boolean(viewer)} />
    <header className={styles.hero}><div className={styles.heroInner}>
      <div className={styles.heroCopy}><p className={styles.eyebrow}>{isMember ? `Acting as: ${data.organization.display_name}` : formatInstitutionalLabel(data.organization.organization_type)}</p><h1>{data.organization.display_name}</h1><p>{data.organization.summary || "No public institutional summary has been supplied."}</p><div className={styles.heroActions}><Link className={styles.secondaryButton} href="/institutions">Institutional directory</Link>{isMember ? <><a className={styles.primaryButton} href="#workspace">Open workspace</a><Link className={styles.secondaryButton} href="/institutions/individual">Switch to personal capacity</Link></> : null}</div>{isMember ? <nav aria-label="Organization institutional workspace" className={styles.subnav}>{ORGANIZATION_WORKSPACE_NAV.map(([label, href]) => <a href={href} key={href}>{label}</a>)}</nav> : null}</div>
      <aside className={styles.heroAside}><div className={styles.principle}><span>01</span><div><strong>{formatInstitutionalLabel(data.organization.verification_status)}</strong><p>This label applies to the profile’s recorded verification state; inspect individual facets below.</p></div></div><div className={styles.principle}><span>02</span><div><strong>Acting identity remains explicit</strong><p>Every institutional action records the authenticated human and exact represented program.</p></div></div><div className={styles.principle}><span>03</span><div><strong>Verification is not endorsement</strong><p>Moral Trade does not thereby endorse this organization, its mission, effectiveness, or opportunities.</p></div></div></aside>
    </div></header>
    <main className={styles.main} id="workspace">
      {message ? <p className={message.tone === "error" ? styles.errorNotice : styles.successNotice}>{message.text}</p> : null}
      <section className={styles.section} id="overview">
        <InstitutionalSectionHeader eyebrow="Identity" title="Public identity and verification facets" description="Legal existence, domain control, representative identity, authority, payment account, and enhanced transaction review are independent facts." />
        <div className={styles.metricGrid}><InstitutionalMetric label="Programs" value={data.programs.length} /><InstitutionalMetric label="Public opportunities" value={data.opportunities.filter((row) => row.status === "published").length} /><InstitutionalMetric label="Verification facts" value={data.verifications.length} /><InstitutionalMetric label="Active deals" value={data.deals.filter((row) => !["completed","terminated","expired"].includes(row.stage)).length} /></div>
        <InstitutionalKeyValue entries={[["Legal name", data.organization.legal_name || "Not publicly supplied"],["Official domain", data.organization.official_domain || "Not verified"],["Jurisdiction", data.organization.jurisdiction || "Not supplied"],["Registration", data.organization.registration_number || "Not supplied"],["Website", data.organization.website_url ? <a key="site" href={data.organization.website_url} rel="noreferrer">{data.organization.website_url}</a> : "Not supplied"],["Profile status", <InstitutionalStatus key="status" tone={institutionalStatusTone(data.organization.status)}>{formatInstitutionalLabel(data.organization.status)}</InstitutionalStatus>]]} />
        {data.verifications.length ? <div className={styles.grid}>{data.verifications.map((verification) => <article className={styles.card} key={verification.id}><div className={styles.cardHeader}><h3>{formatInstitutionalLabel(verification.facet)}</h3><InstitutionalStatus tone={institutionalStatusTone(verification.status)}>{formatInstitutionalLabel(verification.status)}</InstitutionalStatus></div><p>Method: {formatInstitutionalLabel(verification.method)}</p><p>{verification.review_note || "No public review note."}</p></article>)}</div> : <InstitutionalEmpty>No fact-specific verification record is visible.</InstitutionalEmpty>}
      </section>

      <section className={styles.section} id="programs">
        <InstitutionalSectionHeader eyebrow="Programs" title="Programs and portfolio mandates" description="A program is the unit whose priorities, restrictions, budget, and authority are used in matching and approval decisions." />
        {data.programs.length ? <div className={styles.grid}>{data.programs.map((program) => { const mandates = data.mandates.filter((mandate) => mandate.program_id === program.id); return <article className={styles.card} key={program.id}><div className={styles.cardHeader}><div><h3>{program.name}</h3><p>{program.summary}</p></div><InstitutionalStatus tone={institutionalStatusTone(program.status)}>{formatInstitutionalLabel(program.status)}</InstitutionalStatus></div><p><strong>Mandate:</strong> {program.mandate_summary || "Not summarized"}</p>{mandates[0] ? <><p>Current mandate version {mandates[0].version} · {formatInstitutionalLabel(mandates[0].status)}</p><p>{mandates[0].public_summary}</p></> : <p>No versioned mandate visible.</p>}</article>; })}</div> : <InstitutionalEmpty>No program has been published.</InstitutionalEmpty>}
        {isMember ? <><InstitutionalDisclosure title="Create a program"><form action={runInstitutionalAction} className={styles.formGrid}>{base("create_program", organizationId)}<label>Name<input name="name" required /></label><label>Slug<input name="slug" required /></label><label className={styles.fullSpan}>Summary<textarea name="summary" /></label><label className={styles.fullSpan}>Mandate summary<textarea name="mandateSummary" /></label><div className={`${styles.formActions} ${styles.fullSpan}`}><button className={styles.primaryButton} type="submit">Create exact-scope program</button></div></form></InstitutionalDisclosure>
        <InstitutionalDisclosure title="Record a versioned mandate"><form action={runInstitutionalAction} className={styles.formGrid}>{base("create_mandate", organizationId)}<label>Program<select name="programId" required defaultValue=""><option value="" disabled>Select program</option>{data.programs.map((program) => <option key={program.id} value={program.id}>{program.name}</option>)}</select></label><label>Version<input name="version" type="number" min="1" defaultValue="1" /></label><label>Status<select name="status" defaultValue="draft"><option value="draft">Draft</option><option value="active">Active</option></select></label><label>Title<input name="title" required /></label><label className={styles.fullSpan}>Public summary<textarea name="publicSummary" /></label><label className={styles.fullSpan}>Confidential constraints (JSON)<textarea name="confidentialConstraints" defaultValue="{}" /></label><label>Cause scope<textarea name="causeScope" placeholder="One per line" /></label><label>Permissible resources<textarea name="permissibleResources" /></label><label>Prohibited activities<textarea name="prohibitedActivities" /></label><label>Minimum commitment<input name="minimumCommitment" inputMode="decimal" /></label><label>Maximum commitment<input name="maximumCommitment" inputMode="decimal" /></label><div className={`${styles.formActions} ${styles.fullSpan}`}><button className={styles.primaryButton} type="submit">Record mandate version</button></div></form></InstitutionalDisclosure></> : null}
      </section>

      <section className={styles.section} id="resources">
        <InstitutionalSectionHeader eyebrow="Bottlenecks" title="Resources offered and sought" description="Institutional matching looks for opposite marginal constraints rather than treating shared cause tags as sufficient." />
        {data.resourceProfiles.length ? <div className={styles.grid}>{data.resourceProfiles.map((resource) => <article className={styles.card} key={resource.id}><div className={styles.cardHeader}><div><p className={styles.eyebrow}>{formatInstitutionalLabel(resource.direction)} · {formatInstitutionalLabel(resource.resource_type)}</p><h3>{resource.title}</h3></div><InstitutionalStatus tone={institutionalStatusTone(resource.status)}>{formatInstitutionalLabel(resource.status)}</InstitutionalStatus></div><p>{resource.description}</p><p>{programById.get(resource.program_id)?.name || resource.program_id} · {formatInstitutionalLabel(resource.confidentiality)} · {formatInstitutionalLabel(resource.urgency)}</p>{resource.amount_min_cents != null || resource.amount_max_cents != null ? <p>{resource.amount_min_cents != null ? formatInstitutionalMoney(resource.amount_min_cents, resource.currency) : "Open"} – {resource.amount_max_cents != null ? formatInstitutionalMoney(resource.amount_max_cents, resource.currency) : "Open"}</p> : null}</article>)}</div> : <InstitutionalEmpty>No resource or bottleneck profile is visible.</InstitutionalEmpty>}
        {isMember ? <InstitutionalDisclosure title="Create a resource or bottleneck profile"><form action={runInstitutionalAction} className={styles.formGrid}>{base("create_resource_profile", organizationId)}<label>Program<select name="programId" required defaultValue=""><option value="" disabled>Select program</option>{data.programs.map((program) => <option key={program.id} value={program.id}>{program.name}</option>)}</select></label><label>Direction<select name="direction"><option value="offer">Offer</option><option value="seek">Seek</option></select></label><label>Resource type<select name="resourceType" defaultValue="funding"><option value="funding">Funding</option><option value="grantmaking_capacity">Grantmaking capacity</option><option value="staff_time">Staff time</option><option value="staff_secondment">Staff secondment</option><option value="research">Research</option><option value="operations">Operations</option><option value="data">Data</option><option value="compute">Compute</option><option value="distribution">Distribution</option><option value="introductions">Introductions</option><option value="other">Other</option></select></label><label>Title<input name="title" required /></label><label className={styles.fullSpan}>Description<textarea name="description" /></label><label>Quantity<input name="quantity" type="number" step="any" /></label><label>Unit<input name="unit" /></label><label>Minimum amount<input name="amountMin" inputMode="decimal" /></label><label>Maximum amount<input name="amountMax" inputMode="decimal" /></label><label>Currency<input name="currency" defaultValue="usd" maxLength={3} /></label><label>Urgency<select name="urgency"><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="critical">Critical</option></select></label><label>Confidentiality<select name="confidentiality" defaultValue="confidential_matching"><option value="public">Public</option><option value="verified_only">Verified organizations</option><option value="network_only">Network only</option><option value="invited_only">Invited only</option><option value="confidential_matching">Confidential matching</option><option value="blind_matching">Blind matching</option></select></label><label>Reservation terms (JSON)<textarea name="reservationTerms" defaultValue="{}" /></label><label>Qualifications (JSON)<textarea name="qualifications" defaultValue="{}" /></label><label>Constraints (JSON)<textarea name="constraints" defaultValue="{}" /></label><div className={`${styles.formActions} ${styles.fullSpan}`}><button className={styles.primaryButton} type="submit">Save bottleneck profile</button></div></form></InstitutionalDisclosure> : null}
      </section>

      <section className={styles.section} id="opportunities">
        <InstitutionalSectionHeader eyebrow="Opportunities" title="Institutional opportunities" description="Every opportunity records a no-trade baseline summary and the moral difference that may create gains from trade." />
        {data.opportunities.length ? <div className={styles.grid}>{data.opportunities.map((opportunity) => <article className={styles.card} key={opportunity.id}><div className={styles.cardHeader}><h3>{opportunity.title}</h3><InstitutionalStatus tone={institutionalStatusTone(opportunity.status)}>{formatInstitutionalLabel(opportunity.status)}</InstitutionalStatus></div><p>{opportunity.summary}</p><p><strong>Without trade:</strong> {opportunity.no_trade_summary}</p><p><strong>Why moral views differ:</strong> {opportunity.moral_difference_statement || "Not classified"}</p><p>{formatInstitutionalLabel(opportunity.visibility)}</p></article>)}</div> : <InstitutionalEmpty>No institutional opportunity is visible.</InstitutionalEmpty>}
        {isMember ? <InstitutionalDisclosure title="Create an institutional opportunity"><form action={runInstitutionalAction} className={styles.formGrid}>{base("create_opportunity", organizationId)}<label>Program<select name="programId" required defaultValue=""><option value="" disabled>Select program</option>{data.programs.map((program) => <option key={program.id} value={program.id}>{program.name}</option>)}</select></label><label>Status<select name="status" defaultValue="draft"><option value="draft">Draft</option><option value="authorized">Authorized</option><option value="published">Published</option></select></label><label>Title<input name="title" required /></label><label>Visibility<select name="visibility" defaultValue="confidential_matching"><option value="public">Public</option><option value="verified_only">Verified only</option><option value="network_only">Network only</option><option value="invited_only">Invited only</option><option value="confidential_matching">Confidential matching</option><option value="blind_matching">Blind matching</option></select></label><label className={styles.fullSpan}>Summary<textarea name="summary" /></label><label>Offer profile<select name="offerResourceProfileId" defaultValue=""><option value="">None</option>{data.resourceProfiles.filter((row) => row.direction === "offer").map((row) => <option key={row.id} value={row.id}>{row.title}</option>)}</select></label><label>Seek profile<select name="seekResourceProfileId" defaultValue=""><option value="">None</option>{data.resourceProfiles.filter((row) => row.direction === "seek").map((row) => <option key={row.id} value={row.id}>{row.title}</option>)}</select></label><label className={styles.fullSpan}>No-trade baseline summary<textarea name="noTradeSummary" required /></label><label className={styles.fullSpan}>Difference in moral priorities<textarea name="moralDifferenceStatement" /></label><div className={`${styles.formActions} ${styles.fullSpan}`}><button className={styles.primaryButton} type="submit">Create opportunity</button></div></form></InstitutionalDisclosure> : null}
      </section>

      {isMember ? <section className={styles.section} id="deal-rooms">
        <InstitutionalSectionHeader eyebrow="Deal rooms" title="Institutional trades" description="Binding work proceeds through versioned proposals, exact-scope baselines and approvals, named-person consent, immutable signatures, obligations, evidence, and controlled closeout." />
        {data.deals.length ? <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Deal</th><th>Type</th><th>Stage</th><th>Updated</th></tr></thead><tbody>{data.deals.map((deal) => <tr key={deal.id}><td><Link href={institutionalOrganizationDealHref(organizationId, String(deal.id))}>{deal.title}</Link></td><td>{formatInstitutionalLabel(deal.deal_type)}</td><td><InstitutionalStatus tone={institutionalStatusTone(deal.stage)}>{formatInstitutionalLabel(deal.stage)}</InstitutionalStatus></td><td><InstitutionalDate value={deal.updated_at} /></td></tr>)}</tbody></table></div> : <InstitutionalEmpty>No deal room has been created.</InstitutionalEmpty>}
        <InstitutionalDisclosure title="Create a draft institutional deal"><form action={runInstitutionalAction} className={styles.formGrid}>{base("create_deal", organizationId)}<input name="actingCapacity" type="hidden" value="organization" /><label>Lead program<select name="programId" required defaultValue=""><option value="" disabled>Select program</option>{data.programs.map((program) => <option key={program.id} value={program.id}>{program.name}</option>)}</select></label><label>Deal type<select name="dealType" defaultValue="bilateral_trade"><option value="bilateral_trade">Bilateral trade</option><option value="multi_party_exchange">Multi-party exchange</option><option value="institutional_secondment">Institutional secondment</option><option value="funding_redirect">Funding redirect</option><option value="consortium">Consortium</option><option value="moral_public_good_pool">Moral-public-good pool</option></select></label><label>Classification<select name="classification" defaultValue="unclassified"><option value="unclassified">Unclassified</option><option value="pure_moral_trade">Pure moral trade</option><option value="mixed_moral_trade">Mixed moral trade</option><option value="moral_public_goods_coordination">Moral-public-goods coordination</option><option value="ordinary_mission_exchange">Ordinary mission exchange</option><option value="internal_portfolio_reallocation">Internal portfolio reallocation</option></select></label><label>Visibility<select name="visibility" defaultValue="parties_only"><option value="parties_only">Parties only</option><option value="invited_only">Invited only</option><option value="operator_only">Operator only</option><option value="public">Public</option></select></label><label className={styles.fullSpan}>Title<input name="title" required /></label><label className={styles.fullSpan}>Summary<textarea name="summary" /></label><div className={`${styles.formActions} ${styles.fullSpan}`}><button className={styles.primaryButton} type="submit">Create controlled deal room</button></div></form></InstitutionalDisclosure>
      </section> : null}

      {isMember ? <section className={styles.section} id="authority-and-funds">
        <InstitutionalSectionHeader eyebrow="Authority and funds" title="Scoped authority and commitment accounting" description="Pool approval, legal approval, program approval, and financial reservation are separate permissions and separate records." />
        <div className={styles.twoColumn}><div><h3>Active authority grants</h3>{activeGrants.length ? <div className={styles.grid}>{activeGrants.map((grant) => <article className={styles.card} key={grant.id}><div className={styles.cardHeader}><h3>{programById.get(grant.program_id)?.name || "Organization-wide"}</h3><InstitutionalStatus tone="good">Active</InstitutionalStatus></div><p>{grant.permissions.map(formatInstitutionalLabel).join(" · ")}</p><p>{grant.authority_basis}</p><p>{grant.amount_limit_cents == null ? "No recorded amount limit" : formatInstitutionalMoney(grant.amount_limit_cents, grant.currency)}</p></article>)}</div> : <InstitutionalEmpty>No active authority grant.</InstitutionalEmpty>}</div><div><h3>Budget accounts</h3>{data.budgetAccounts.length ? <div className={styles.grid}>{data.budgetAccounts.map((account) => <article className={styles.card} key={account.id}><div className={styles.cardHeader}><h3>{account.name}</h3><InstitutionalStatus tone={institutionalStatusTone(account.status)}>{formatInstitutionalLabel(account.status)}</InstitutionalStatus></div><p>{formatInstitutionalMoney(account.authorized_cents, account.currency)} authorized</p><p>{programById.get(account.program_id)?.name || "Organization-wide"}</p></article>)}</div> : <InstitutionalEmpty>No commitment account.</InstitutionalEmpty>}</div></div>
        <InstitutionalDisclosure title="Create a commitment account"><form action={runInstitutionalAction} className={styles.formGrid}>{base("create_budget_account", organizationId)}<label>Program<select name="programId" defaultValue=""><option value="">Organization-wide</option>{data.programs.map((program) => <option key={program.id} value={program.id}>{program.name}</option>)}</select></label><label>Name<input name="name" required /></label><label>Authorized amount<input name="authorizedAmount" inputMode="decimal" required /></label><label>Currency<input name="currency" defaultValue="usd" maxLength={3} /></label><div className={`${styles.formActions} ${styles.fullSpan}`}><button className={styles.primaryButton} type="submit">Create commitment account</button></div></form></InstitutionalDisclosure>
      </section> : null}

      {isMember && viewer ? <InstitutionalOrganizationAdministration data={data} organizationId={organizationId} /> : null}

      {isMember ? <section className={styles.section} id="integrations">
        <InstitutionalSectionHeader eyebrow="Integrations" title="Enterprise integrations" description="Configuration may contain non-secret identifiers only. Credentials remain in supported secret stores and are referenced indirectly; webhook events are allowlisted." />
        {data.integrations.length ? <div className={styles.grid}>{data.integrations.map((integration) => <article className={styles.card} key={integration.id}><div className={styles.cardHeader}><h3>{integration.name}</h3><InstitutionalStatus tone={institutionalStatusTone(integration.status)}>{formatInstitutionalLabel(integration.status)}</InstitutionalStatus></div><p>{formatInstitutionalLabel(integration.integration_type)} · credential reference {integration.credential_reference || "not set"}</p><details className={styles.commandPayload}><summary>Non-secret configuration</summary><pre>{JSON.stringify(integration.configuration, null, 2)}</pre></details></article>)}</div> : <InstitutionalEmpty>No institutional integration.</InstitutionalEmpty>}
        <InstitutionalDisclosure title="Create an integration"><form action={runInstitutionalAction} className={styles.formGrid}>{base("create_integration", organizationId)}<label>Program<select name="programId" defaultValue=""><option value="">Organization-wide</option>{data.programs.map((program) => <option key={program.id} value={program.id}>{program.name}</option>)}</select></label><label>Type<select name="integrationType"><option value="webhook">Webhook</option><option value="api">API</option><option value="esignature">E-signature</option><option value="payment">Payment reference</option><option value="registry">Registry</option><option value="storage">Storage</option><option value="other">Other</option></select></label><label>Name<input name="name" required /></label><label>Credential reference<input name="credentialReference" placeholder="vercel:INSTITUTIONAL_SIGNING_SECRET" /></label><label className={styles.fullSpan}>Non-secret configuration (JSON)<textarea name="configuration" defaultValue="{}" /></label><label>Status<select name="status"><option value="draft">Draft</option><option value="active">Active</option><option value="disabled">Disabled</option></select></label><div className={`${styles.formActions} ${styles.fullSpan}`}><button className={styles.primaryButton} type="submit">Create secret-free integration</button></div></form></InstitutionalDisclosure>
        {data.webhooks.length ? <div className={styles.grid}>{data.webhooks.map((webhook) => <article className={styles.card} key={webhook.id}><div className={styles.cardHeader}><h3>{webhook.endpoint_url}</h3><InstitutionalStatus tone={institutionalStatusTone(webhook.status)}>{formatInstitutionalLabel(webhook.status)}</InstitutionalStatus></div><p>{Array.isArray(webhook.supported_events) ? webhook.supported_events.join(" · ") : "No supported events"}</p><p>Secret reference: {webhook.secret_reference}</p></article>)}</div> : <InstitutionalEmpty>No signed webhook has been configured.</InstitutionalEmpty>}
        {data.integrations.length ? <InstitutionalDisclosure title="Create a signed webhook"><form action={runInstitutionalAction} className={styles.formGrid}>{base("create_webhook", organizationId)}<label>Integration<select name="integrationId" required defaultValue=""><option value="" disabled>Select integration</option>{data.integrations.map((integration) => <option key={integration.id} value={integration.id}>{integration.name}</option>)}</select></label><label>Endpoint URL<input name="endpointUrl" type="url" required placeholder="https://example.org/webhooks/moral-trade" /></label><label className={styles.fullSpan}>Supported events (one per line)<textarea name="supportedEvents" required defaultValue={`deal.signed
deal.completed
pool.activated`} /></label><label>Secret reference<input name="secretReference" required placeholder="vercel:INSTITUTIONAL_WEBHOOK_SECRET" /></label><label>Status<select name="status" defaultValue="draft"><option value="draft">Draft</option><option value="active">Active</option><option value="disabled">Disabled</option><option value="revoked">Revoked</option></select></label><div className={`${styles.formActions} ${styles.fullSpan}`}><button className={styles.primaryButton} type="submit">Create allowlisted webhook</button></div></form></InstitutionalDisclosure> : null}
        <p className={styles.callout}>Moral Trade does not custody institutional funds in this release. Payment integrations may record external-provider references, but they cannot create platform escrow, payouts, or custodial balances.</p>
      </section> : null}
    </main><SiteFooter />
  </div>;
}
