import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { chromium } from "playwright";
import { createServerClient } from "@supabase/ssr";
import { createClient } from "@supabase/supabase-js";
const required=(n)=>{const v=process.env[n]?.trim();if(!v)throw new Error(`Missing ${n}`);return v};
const load=(p)=>JSON.parse(readFileSync(p,"utf8"));
const host=(u)=>new URL(u).hostname.replace(/^www\./,"");
async function cookieValues(session,url,key){const out=[];const s=createServerClient(url,key,{cookies:{getAll:()=>[],setAll:(v)=>out.splice(0,out.length,...v)}});const{error}=await s.auth.setSession({access_token:session.access_token,refresh_token:session.refresh_token});if(error)throw error;return out}
function cookies(values,base){const urls=[base],h=new URL(base).hostname;if(h==="moraltrade.org")urls.push("https://www.moraltrade.org");if(h==="www.moraltrade.org")urls.push("https://moraltrade.org");return urls.flatMap(url=>values.map(({name,value})=>({name,value,url,httpOnly:true,secure:true,sameSite:"Lax"})))}
async function signIn(email,password,url,key){const c=createClient(url,key,{auth:{autoRefreshToken:false,detectSessionInUrl:false,persistSession:false}});const{data,error}=await c.auth.signInWithPassword({email,password});if(error||!data.session)throw new Error(error?.message||"no session");return{client:c,session:data.session}}
const bases=required("I782_BASE_URLS").split(",").map(v=>v.trim()).filter(Boolean),url=required("NEXT_PUBLIC_SUPABASE_URL"),key=required("NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY"),service=required("SUPABASE_SERVICE_ROLE_KEY"),password=required("I782_QA_PASSWORD"),state=load(required("I782_AUTH_STATE")),creator=state.users.creator,probe=state.users[required("I782_PROBE_ROLE")],out=required("I782_AUTH_UAT_DIR");mkdirSync(out,{recursive:true,mode:0o700});
const routes=["/profile","/create","/dashboard","/feed"],viewports=[{name:"desktop",width:1440,height:1000},{name:"mobile",width:390,height:844}],markers=[creator.email,"Issue 782 synthetic creator","QA DAC Product Creator"],browser=await chromium.launch({headless:true});let checks=0,probeUsed=false;
try{for(const base of bases){const valid=await signIn(creator.email,password,url,key),vals=await cookieValues(valid.session,url,key),cs=cookies(vals,base);let identity=0;for(const vp of viewports){const context=await browser.newContext({baseURL:base,viewport:vp});context.setDefaultTimeout(15000);context.setDefaultNavigationTimeout(30000);await context.addCookies([...cs,...cookies([{name:"mt_walkthrough_seen",value:"1"}],base)]);for(const route of routes){const page=await context.newPage(),diag={console:[],page:[],request:[]};page.on("console",m=>{if(m.type()==="error")diag.console.push(m.text())});page.on("pageerror",e=>diag.page.push(e.message));page.on("requestfailed",r=>{const f=r.failure()?.errorText||"failed";if(host(r.url())===host(base)&&!/ERR_ABORTED/i.test(f))diag.request.push(`${r.method()} ${new URL(r.url()).pathname} ${f}`)});const response=await page.goto(route,{waitUntil:"domcontentloaded"}),status=response?.status()||0;if(!status||status>=500)throw new Error(`${route}:${status}`);if(/\/(login|sign-in|signin)(?:[/?#]|$)/i.test(page.url()))throw new Error(`valid signed out:${route}`);const text=await page.locator("body").innerText();if(markers.some(m=>text.includes(m)))identity++;const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);if(overflow>1||diag.console.length||diag.page.length||diag.request.length)throw new Error(JSON.stringify({route,overflow,diag}));await page.screenshot({path:join(out,`${new URL(base).hostname}-${vp.name}-${route.slice(1)}.png`),fullPage:true});await page.close();checks++}await context.close()}await valid.client.auth.signOut({scope:"local"});if(identity<1)throw new Error(`identity not rendered:${base}`);
const invalid=await browser.newContext({baseURL:base,viewport:viewports[1]});await invalid.addCookies(cookies(vals.map(c=>({...c,value:"invalid-issue782-session"})),base));const ip=await invalid.newPage(),ir=await ip.goto("/dashboard",{waitUntil:"domcontentloaded"}),it=await ip.locator("body").innerText();if(!(/\/(login|sign-in|signin)(?:[/?#]|$)/i.test(ip.url())||[401,403].includes(ir?.status()||0)||/sign in|log in|authentication required/i.test(it))||markers.some(m=>it.includes(m)))throw new Error("malformed session not closed");await invalid.close();
if(!probeUsed){const ps=await signIn(probe.email,password,url,key),pv=await cookieValues(ps.session,url,key),admin=createClient(url,service,{auth:{autoRefreshToken:false,detectSessionInUrl:false,persistSession:false}});const{error}=await admin.auth.admin.signOut(ps.session.access_token,"global");if(error)throw new Error(`admin signout:${error.message}`);const expired=await browser.newContext({baseURL:base,viewport:viewports[1]});await expired.addCookies(cookies(pv,base));const ep=await expired.newPage(),er=await ep.goto("/dashboard",{waitUntil:"domcontentloaded"}),et=await ep.locator("body").innerText();if(!(/\/(login|sign-in|signin)(?:[/?#]|$)/i.test(ep.url())||[401,403].includes(er?.status()||0)||/sign in|log in|authentication required/i.test(et))||et.includes(probe.email))throw new Error("globally signed-out session not closed");await expired.close();await ps.client.auth.signOut({scope:"local"}).catch(()=>{});probeUsed=true}}
}finally{await browser.close()}
const summary={schemaVersion:3,bases:bases.map(b=>new URL(b).hostname),routeChecks:checks,malformedSessionFailedClosed:true,globallySignedOutSessionFailedClosed:true,noUnauthorizedSyntheticIdentityFlash:true,completedAt:new Date().toISOString()};writeFileSync(join(out,"auth-uat-summary.json"),JSON.stringify(summary,null,2)+"\n",{mode:0o600});console.log(JSON.stringify(summary));
