-- Moral Goods Group Buying persistent records.
-- This migration is intentionally additive and does not alter existing pledge-swap tables.

create table if not exists public.moral_goods_action_templates (
  id text primary key,
  name text not null,
  version text not null,
  category text not null check (category in ('diet', 'donation', 'volunteering', 'advocacy', 'offset', 'custom_admin_only')),
  description text not null,
  moral_view_or_cause_area_summary text,
  safety_review_status text not null check (safety_review_status in ('pending', 'approved', 'rejected', 'requires_changes')),
  methodology_review_status text not null check (methodology_review_status in ('pending', 'approved', 'rejected', 'requires_changes')),
  participant_welfare_review_status text not null check (participant_welfare_review_status in ('pending', 'approved', 'rejected', 'requires_changes')),
  behavior_change_equivalence_key text,
  raw_unit_name text not null,
  baseline_fields_schema jsonb not null default '{}'::jsonb,
  verification_fields_schema jsonb not null default '{}'::jsonb,
  eligibility_rules_schema jsonb not null default '{}'::jsonb,
  default_moral_impact_weight_bps integer not null check (default_moral_impact_weight_bps >= 0),
  default_persistence_multiplier_bps integer not null check (default_persistence_multiplier_bps >= 0),
  allowed_verification_standards text[] not null default array['light', 'standard', 'strong'],
  is_admin_approved boolean not null default false,
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moral_goods_frozen_policy_components (
  id text primary key,
  component_type text not null,
  component_version text not null,
  canonical_json jsonb not null,
  canonicalization_policy_version text not null,
  component_hash text not null unique,
  hash_algorithm text not null default 'sha256',
  public_export_json jsonb,
  private_policy_snapshot_ref text,
  redaction_policy_version text not null,
  status text not null check (status in ('draft', 'frozen', 'superseded', 'revoked_for_future_use')),
  created_by uuid,
  frozen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moral_goods_frozen_policy_bundles (
  id text primary key,
  purchase_envelope_type text,
  purchase_envelope_id text,
  bundle_type text not null,
  component_manifest_json jsonb not null,
  bundle_canonical_json jsonb not null,
  bundle_hash text not null unique,
  hash_algorithm text not null default 'sha256',
  canonicalization_policy_version text not null,
  public_bundle_export_json jsonb,
  private_policy_snapshot_ref text,
  compatibility_check_status text not null check (compatibility_check_status in ('pending', 'passed', 'failed', 'waived_dev_only')),
  status text not null check (status in ('draft', 'frozen', 'superseded', 'revoked_for_future_use')),
  created_by uuid,
  frozen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moral_goods_purchase_envelope_registry (
  id text primary key,
  envelope_type text not null check (envelope_type in ('group_buy_round', 'crowdfunded_pledge_swap_lot', 'crowdfunded_pledge_swap_basket', 'crowdfunded_pledge_swap_basket_item', 'pledge_swap_agreement_adapter', 'standing_microfund_pool', 'other')),
  envelope_entity_id text not null,
  parent_envelope_type text,
  parent_envelope_id text,
  public_envelope_id text not null unique,
  title_snapshot text not null,
  currency text not null,
  lifecycle_status text not null,
  lifecycle_state_group text not null check (lifecycle_state_group in ('draft_review', 'funding', 'funded_awaiting_acceptance', 'accepted_not_active', 'active', 'evidence_due', 'under_review', 'settling', 'completed', 'released_expired_cancelled', 'blocked_paused')),
  status_category text not null,
  enabled_feature_modules_snapshot_json jsonb not null default '[]'::jsonb,
  frozen_policy_bundle_id text references public.moral_goods_frozen_policy_bundles(id),
  public_snapshot_hash text,
  private_policy_snapshot_ref text,
  projection_version integer not null default 1,
  projection_reconciled_at timestamptz,
  projection_reconciliation_status text not null default 'not_checked' check (projection_reconciliation_status in ('not_checked', 'consistent', 'stale', 'mismatch', 'repair_required')),
  purchase_envelope_architecture_version text not null,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (envelope_type, envelope_entity_id)
);

create table if not exists public.moral_goods_group_buy_rounds (
  id text primary key,
  title text not null,
  slug text not null unique,
  description text not null,
  action_template_id text not null references public.moral_goods_action_templates(id),
  action_template_snapshot_json jsonb not null,
  impact_formula_version text not null,
  settlement_formula_version text not null,
  pricing_terms_snapshot_json jsonb not null,
  participant_terms_snapshot_json jsonb not null,
  funder_terms_snapshot_json jsonb not null,
  round_snapshot_hash text not null unique,
  round_snapshot_canonical_json jsonb not null,
  public_round_snapshot_json jsonb not null,
  private_policy_snapshot_ref text,
  status text not null check (status in ('draft', 'under_review', 'funding', 'enrolling', 'ready_to_clear', 'active', 'verifying', 'settling', 'settled', 'cancelled')),
  safety_review_status text not null check (safety_review_status in ('pending', 'approved', 'rejected', 'requires_changes')),
  methodology_review_status text not null check (methodology_review_status in ('pending', 'approved', 'rejected', 'requires_changes')),
  participant_welfare_review_status text not null check (participant_welfare_review_status in ('pending', 'approved', 'rejected', 'requires_changes')),
  group_buy_validity_mode text not null check (group_buy_validity_mode in ('instant_valid', 'team_threshold')),
  team_activation_scope text not null check (team_activation_scope in ('none', 'funder_only', 'participant_only', 'dual_sided')),
  team_activation_effect text not null check (team_activation_effect in ('none', 'eligibility_only', 'reserve_capacity_until_launch', 'activate_and_select_if_clear')),
  team_activation_policy_snapshot_json jsonb,
  minimum_expected_adjusted_units_milli bigint not null check (minimum_expected_adjusted_units_milli >= 0),
  maximum_cost_per_adjusted_unit_minor integer not null check (maximum_cost_per_adjusted_unit_minor >= 0),
  unit_price_minor integer not null check (unit_price_minor >= 0),
  participant_payout_cap_minor integer not null check (participant_payout_cap_minor >= 0),
  participant_payout_reserve_minor integer not null check (participant_payout_reserve_minor >= 0),
  reserve_policy_snapshot_json jsonb not null,
  funding_shortfall_policy_snapshot_json jsonb not null,
  no_trade_baseline_policy_snapshot_json jsonb not null,
  impact_claims_policy_snapshot_json jsonb not null,
  currency text not null,
  display_timezone text not null,
  launch_deadline timestamptz not null,
  enrollment_deadline timestamptz not null,
  verification_submission_deadline timestamptz not null,
  dispute_deadline timestamptz not null,
  reauthorization_deadline timestamptz,
  expected_settlement_at timestamptz,
  expected_payout_at timestamptz,
  action_start_at timestamptz not null,
  action_end_at timestamptz not null,
  verification_standard text not null check (verification_standard in ('light', 'standard', 'strong')),
  moral_impact_weight_default_bps integer not null check (moral_impact_weight_default_bps >= 0),
  persistence_multiplier_default_bps integer not null check (persistence_multiplier_default_bps >= 0),
  risk_tier text check (risk_tier in ('dev_simulated', 'private_beta', 'limited_public', 'general_public')),
  operational_pause_status text not null default 'not_paused' check (operational_pause_status in ('not_paused', 'intake_paused', 'money_movement_paused', 'fully_paused')),
  public_report_visibility text not null,
  enabled_feature_modules_snapshot_json jsonb not null default '[]'::jsonb,
  purchase_envelope_registry_id text references public.moral_goods_purchase_envelope_registry(id),
  frozen_policy_bundle_id text references public.moral_goods_frozen_policy_bundles(id),
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (action_start_at < action_end_at),
  check (launch_deadline <= enrollment_deadline),
  check (enrollment_deadline <= action_start_at),
  check (action_end_at <= verification_submission_deadline),
  check (verification_submission_deadline <= dispute_deadline)
);

create table if not exists public.moral_goods_funding_source_commitments (
  id text primary key,
  purchase_envelope_type text not null,
  purchase_envelope_id text not null,
  funding_source_type text not null check (funding_source_type in ('ordinary_funder_pledge', 'crowdfunded_micro_pledge', 'standing_microfund_allocation', 'sponsor_matching_pool', 'sponsor_gap_fill', 'platform_reserve', 'dev_simulated_reserve')),
  funding_source_id text not null,
  funder_user_id uuid,
  sponsor_user_id uuid,
  amount_authorized_minor integer not null default 0 check (amount_authorized_minor >= 0),
  amount_reserved_minor integer not null default 0 check (amount_reserved_minor >= 0),
  amount_committed_minor integer not null default 0 check (amount_committed_minor >= 0),
  amount_charged_minor integer not null default 0 check (amount_charged_minor >= 0),
  amount_released_minor integer not null default 0 check (amount_released_minor >= 0),
  currency text not null,
  reserve_eligibility text not null,
  constraints_snapshot_json jsonb not null default '{}'::jsonb,
  accepted_routing_policy_snapshot_json jsonb,
  authorization_expires_at timestamptz,
  funding_source_status text not null,
  activation_status text not null default 'instant_valid' check (activation_status in ('instant_valid', 'pending_team', 'activated', 'expired', 'cancelled', 'blocked')),
  idempotency_key text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (funding_source_type, funding_source_id)
);

create table if not exists public.moral_goods_participant_action_commitments (
  id text primary key,
  purchase_envelope_type text not null,
  purchase_envelope_id text not null,
  participant_user_id uuid,
  participant_user_hash text not null,
  participant_enrollment_id text,
  basket_item_id text,
  source_pledge_swap_agreement_id text,
  action_template_id text not null references public.moral_goods_action_templates(id),
  action_template_snapshot_json jsonb not null,
  action_window_start_at timestamptz not null,
  action_window_end_at timestamptz not null,
  baseline_snapshot_ref text,
  expected_raw_units integer check (expected_raw_units >= 0),
  expected_adjusted_units_milli bigint check (expected_adjusted_units_milli >= 0),
  participant_visible_action_summary text not null,
  participant_preacceptance_status text,
  participant_acceptance_status text,
  acceptance_expires_at timestamptz,
  action_start_permission_status text,
  public_identity_visibility text not null default 'anonymous',
  participant_visible_public_id text,
  private_action_obligation_snapshot_ref text,
  commitment_status text not null,
  accepted_terms_acceptance_id text,
  verification_decision_id text,
  credited_action_unit_status text not null default 'not_started',
  privacy_display_policy_snapshot_json jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (action_window_start_at < action_window_end_at)
);

create table if not exists public.moral_goods_credited_action_units (
  id text primary key,
  enrollment_id text,
  participant_action_commitment_id text references public.moral_goods_participant_action_commitments(id),
  purchase_envelope_type text,
  purchase_envelope_id text,
  source_feature text not null check (source_feature in ('group_buying', 'pledge_swap', 'other_moral_trade')),
  source_commitment_id text,
  participant_user_id uuid,
  participant_user_hash text not null,
  action_template_id text not null references public.moral_goods_action_templates(id),
  raw_unit_key text not null unique,
  action_window_start_at timestamptz not null,
  action_window_end_at timestamptz not null,
  raw_units_credited integer not null check (raw_units_credited >= 0),
  source_verification_decision_id text,
  credited_to_settlement_id text,
  de_duplication_status text not null check (de_duplication_status in ('pending', 'clear', 'duplicate_blocked', 'de_duplicated', 'credited', 'reversed')),
  duplicate_of_credited_action_unit_id text references public.moral_goods_credited_action_units(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (action_window_start_at < action_window_end_at)
);

create table if not exists public.moral_goods_consideration_obligations (
  id text primary key,
  purchase_envelope_type text not null,
  purchase_envelope_id text not null,
  settlement_id text,
  enrollment_id text,
  basket_item_id text,
  participant_action_commitment_id text references public.moral_goods_participant_action_commitments(id),
  participant_user_id uuid,
  beneficiary_type text not null,
  beneficiary_user_id uuid,
  donation_recipient_id text,
  consideration_type text not null,
  trigger_policy_snapshot_json jsonb not null,
  reserve_policy_snapshot_json jsonb not null,
  amount_promised_minor integer not null default 0 check (amount_promised_minor >= 0),
  amount_reserved_minor integer not null default 0 check (amount_reserved_minor >= 0),
  amount_earned_minor integer not null default 0 check (amount_earned_minor >= 0),
  amount_executed_minor integer not null default 0 check (amount_executed_minor >= 0),
  amount_released_minor integer not null default 0 check (amount_released_minor >= 0),
  currency text not null,
  obligation_status text not null,
  source_funding_summary_hash text,
  calculation_input_hash text,
  calculation_output_hash text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moral_goods_settlement_plans (
  id text primary key,
  purchase_envelope_type text not null,
  purchase_envelope_id text not null,
  round_id text,
  settlement_id text,
  plan_status text not null check (plan_status in ('draft', 'computed', 'approved', 'superseded', 'executing', 'executed', 'failed', 'cancelled')),
  frozen_policy_bundle_hash text not null,
  calculation_input_hash text not null,
  calculation_output_hash text,
  funding_source_set_hash text not null,
  credited_action_unit_set_hash text,
  consideration_obligation_set_hash text not null,
  fee_withholding_line_item_set_hash text,
  donation_operation_set_hash text,
  payout_operation_set_hash text,
  release_operation_set_hash text,
  ledger_transaction_set_hash text,
  reserve_check_status text not null,
  recipient_funding_compatibility_status text not null,
  fee_ratio_check_status text not null,
  verification_burden_check_status text not null,
  approved_by_user_id uuid,
  approved_at timestamptz,
  executed_at timestamptz,
  superseded_by_settlement_plan_id text references public.moral_goods_settlement_plans(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (purchase_envelope_type, purchase_envelope_id, calculation_input_hash)
);

create table if not exists public.moral_goods_crowdfunded_pledge_swap_lots (
  id text primary key,
  round_id text references public.moral_goods_group_buy_rounds(id),
  basket_id text,
  participant_proposal_id text,
  title text not null,
  slug text not null unique,
  action_template_id text not null references public.moral_goods_action_templates(id),
  action_template_snapshot_json jsonb not null,
  participant_user_id uuid,
  lot_kind text not null check (lot_kind in ('single_participant_pledge_swap', 'small_cohort_pledge_swap')),
  consideration_type text not null check (consideration_type in ('charitable_donation', 'participant_payout', 'mixed')),
  consideration_recipient_policy text not null,
  participant_recipient_choice_required boolean not null default false,
  participant_selected_donation_recipient_id text,
  approved_donation_recipient_list_snapshot_json jsonb,
  target_total_consideration_minor integer not null check (target_total_consideration_minor >= 0),
  minimum_clearing_consideration_minor integer not null check (minimum_clearing_consideration_minor >= 0),
  amount_authorized_minor integer not null default 0 check (amount_authorized_minor >= 0),
  amount_committed_minor integer not null default 0 check (amount_committed_minor >= 0),
  amount_captured_minor integer not null default 0 check (amount_captured_minor >= 0),
  amount_released_minor integer not null default 0 check (amount_released_minor >= 0),
  amount_donated_minor integer not null default 0 check (amount_donated_minor >= 0),
  amount_paid_to_participant_minor integer not null default 0 check (amount_paid_to_participant_minor >= 0),
  currency text not null,
  micro_pledge_min_minor integer not null check (micro_pledge_min_minor >= 0),
  micro_pledge_default_minor integer not null check (micro_pledge_default_minor >= 0),
  micro_pledge_max_minor integer not null check (micro_pledge_max_minor >= 0),
  standing_microfund_pool_eligible boolean not null default false,
  funding_deadline timestamptz not null,
  participant_acceptance_deadline timestamptz,
  action_start_at timestamptz not null,
  action_end_at timestamptz not null,
  verification_submission_deadline timestamptz not null,
  dispute_deadline timestamptz not null,
  donation_or_payout_reserve_minor integer not null default 0 check (donation_or_payout_reserve_minor >= 0),
  donation_or_payout_reserve_status text not null,
  verification_standard text not null check (verification_standard in ('light', 'standard', 'strong')),
  expected_raw_units integer not null check (expected_raw_units >= 0),
  expected_adjusted_units_milli bigint,
  public_lot_snapshot_json jsonb not null,
  private_policy_snapshot_ref text,
  lot_snapshot_canonical_json jsonb not null,
  lot_snapshot_hash text not null unique,
  purchase_envelope_registry_id text references public.moral_goods_purchase_envelope_registry(id),
  frozen_policy_bundle_id text references public.moral_goods_frozen_policy_bundles(id),
  participant_action_commitment_id text references public.moral_goods_participant_action_commitments(id),
  participant_publicity_status text not null default 'default_private',
  status text not null,
  safety_review_status text not null,
  methodology_review_status text not null,
  participant_welfare_review_status text not null,
  jurisdiction_check_status text not null,
  public_report_visibility text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (action_start_at < action_end_at),
  check (funding_deadline <= action_start_at),
  check (action_end_at <= verification_submission_deadline),
  check (verification_submission_deadline <= dispute_deadline)
);

create table if not exists public.moral_goods_crowdfunded_pledge_swap_micro_pledges (
  id text primary key,
  lot_id text references public.moral_goods_crowdfunded_pledge_swap_lots(id),
  basket_id text,
  standing_microfund_pool_id text,
  standing_microfund_allocation_id text,
  allocation_source text not null,
  funder_user_id uuid,
  amount_authorized_minor integer not null default 0 check (amount_authorized_minor >= 0),
  amount_committed_minor integer not null default 0 check (amount_committed_minor >= 0),
  amount_charged_minor integer not null default 0 check (amount_charged_minor >= 0),
  amount_released_minor integer not null default 0 check (amount_released_minor >= 0),
  currency text not null,
  activation_status text not null default 'instant_valid',
  payment_authorization_id text,
  payment_authorization_expires_at timestamptz,
  accepted_donation_recipient_scope_snapshot_json jsonb,
  allocation_review_mode text,
  allocation_notice_expires_at timestamptz,
  funder_terms_accepted_at timestamptz,
  micro_pledge_status text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moral_goods_donation_recipients (
  id text primary key,
  name text not null,
  legal_name text,
  jurisdiction_scope text not null,
  cause_area text not null,
  effective_charity_evaluation_ref text,
  effective_charity_evaluation_checked_at timestamptz,
  effective_charity_evaluation_expires_at timestamptz,
  approved_payment_destination_ref text,
  payment_destination_verified_at timestamptz,
  payment_destination_expires_at timestamptz,
  due_diligence_status text not null,
  due_diligence_checked_at timestamptz,
  due_diligence_expires_at timestamptz,
  sanctions_aml_status text not null,
  sanctions_aml_checked_at timestamptz,
  sanctions_aml_expires_at timestamptz,
  donation_receipt_policy_snapshot_json jsonb,
  public_summary text not null,
  private_notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moral_goods_pledge_swap_donation_operations (
  id text primary key,
  lot_id text references public.moral_goods_crowdfunded_pledge_swap_lots(id),
  settlement_id text,
  donation_recipient_id text references public.moral_goods_donation_recipients(id),
  amount_minor integer not null check (amount_minor >= 0),
  currency text not null,
  provider_name text not null,
  provider_operation_ref text,
  idempotency_key text unique,
  donation_receipt_ref text,
  donor_of_record_type text,
  donation_tax_receipt_user_id uuid,
  donation_receipt_json_redacted jsonb,
  donation_failure_policy_snapshot_hash text,
  status text not null,
  last_error_redacted text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moral_goods_crowdfunded_pledge_swap_baskets (
  id text primary key,
  round_id text references public.moral_goods_group_buy_rounds(id),
  title text not null,
  slug text not null unique,
  basket_kind text not null,
  action_template_id text not null references public.moral_goods_action_templates(id),
  action_template_snapshot_json jsonb not null,
  lot_count_target integer not null check (lot_count_target >= 0),
  lot_count_minimum_to_clear integer not null check (lot_count_minimum_to_clear >= 0),
  lot_count_settled integer not null default 0 check (lot_count_settled >= 0),
  per_lot_consideration_minor integer not null check (per_lot_consideration_minor >= 0),
  target_total_consideration_minor integer not null check (target_total_consideration_minor >= 0),
  minimum_clearing_consideration_minor integer not null check (minimum_clearing_consideration_minor >= 0),
  amount_authorized_minor integer not null default 0 check (amount_authorized_minor >= 0),
  amount_committed_minor integer not null default 0 check (amount_committed_minor >= 0),
  amount_captured_minor integer not null default 0 check (amount_captured_minor >= 0),
  amount_released_minor integer not null default 0 check (amount_released_minor >= 0),
  amount_donated_minor integer not null default 0 check (amount_donated_minor >= 0),
  amount_paid_to_participants_minor integer not null default 0 check (amount_paid_to_participants_minor >= 0),
  currency text not null,
  consideration_type text not null,
  consideration_recipient_policy text not null,
  approved_donation_recipient_list_snapshot_json jsonb,
  participant_recipient_choice_policy_snapshot_json jsonb,
  micro_pledge_min_minor integer not null,
  micro_pledge_default_minor integer not null,
  micro_pledge_max_minor integer not null,
  standing_microfund_pool_eligible boolean not null default false,
  sponsor_gap_fill_commitment_id text,
  funding_deadline timestamptz not null,
  participant_acceptance_deadline timestamptz,
  action_start_at timestamptz not null,
  action_end_at timestamptz not null,
  verification_submission_deadline timestamptz not null,
  dispute_deadline timestamptz not null,
  donation_or_payout_reserve_minor integer not null default 0,
  donation_or_payout_reserve_status text not null,
  verification_standard text not null,
  expected_raw_units_total integer not null,
  expected_adjusted_units_total_milli bigint,
  public_basket_snapshot_json jsonb not null,
  private_policy_snapshot_ref text,
  basket_snapshot_canonical_json jsonb not null,
  basket_snapshot_hash text not null unique,
  purchase_envelope_registry_id text references public.moral_goods_purchase_envelope_registry(id),
  frozen_policy_bundle_id text references public.moral_goods_frozen_policy_bundles(id),
  status text not null,
  safety_review_status text not null,
  methodology_review_status text not null,
  participant_welfare_review_status text not null,
  jurisdiction_check_status text not null,
  public_report_visibility text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moral_goods_crowdfunded_pledge_swap_basket_items (
  id text primary key,
  basket_id text not null references public.moral_goods_crowdfunded_pledge_swap_baskets(id),
  lot_id text references public.moral_goods_crowdfunded_pledge_swap_lots(id),
  action_commitment_id text references public.moral_goods_participant_action_commitments(id),
  participant_user_id uuid,
  donation_recipient_id text references public.moral_goods_donation_recipients(id),
  participant_selected_donation_recipient_id text references public.moral_goods_donation_recipients(id),
  item_sequence integer not null,
  item_action_obligation_snapshot_json jsonb not null,
  item_consideration_minor integer not null check (item_consideration_minor >= 0),
  item_expected_raw_units integer not null check (item_expected_raw_units >= 0),
  item_expected_adjusted_units_milli bigint,
  item_status text not null,
  replacement_of_basket_item_id text references public.moral_goods_crowdfunded_pledge_swap_basket_items(id),
  verification_decision_id text,
  credited_to_settlement_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (basket_id, item_sequence)
);

create table if not exists public.moral_goods_standing_microfund_pools (
  id text primary key,
  funder_user_id uuid,
  title text not null,
  currency text not null,
  period text not null check (period in ('monthly', 'weekly', 'one_time_budget')),
  period_limit_minor integer not null check (period_limit_minor >= 0),
  remaining_period_budget_minor integer not null check (remaining_period_budget_minor >= 0),
  per_lot_cap_minor integer not null check (per_lot_cap_minor >= 0),
  per_basket_cap_minor integer not null check (per_basket_cap_minor >= 0),
  per_basket_item_cap_minor integer check (per_basket_item_cap_minor >= 0),
  minimum_allocation_minor integer not null check (minimum_allocation_minor >= 0),
  cause_area_allowlist_json jsonb,
  action_template_allowlist_json jsonb,
  consideration_type_allowlist_json jsonb,
  donation_recipient_allowlist_json jsonb,
  allocation_strategy text not null,
  allocation_review_mode text not null check (allocation_review_mode in ('auto_lock', 'preview_then_lock', 'manual_approval_required')),
  allocation_policy_snapshot_json jsonb not null,
  payment_funding_source_ref text,
  payment_authorization_id text,
  payment_authorization_expires_at timestamptz,
  wallet_or_internal_balance_account_id text,
  internal_balance_legal_status text not null default 'not_used',
  auto_renew_status text not null,
  next_period_starts_at timestamptz,
  funder_terms_accepted_at timestamptz,
  status text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moral_goods_standing_microfund_allocations (
  id text primary key,
  standing_microfund_pool_id text not null references public.moral_goods_standing_microfund_pools(id),
  lot_id text references public.moral_goods_crowdfunded_pledge_swap_lots(id),
  basket_id text references public.moral_goods_crowdfunded_pledge_swap_baskets(id),
  basket_item_id text references public.moral_goods_crowdfunded_pledge_swap_basket_items(id),
  micro_pledge_id text references public.moral_goods_crowdfunded_pledge_swap_micro_pledges(id),
  amount_allocated_minor integer not null check (amount_allocated_minor >= 0),
  amount_authorized_minor integer not null default 0 check (amount_authorized_minor >= 0),
  amount_charged_minor integer not null default 0 check (amount_charged_minor >= 0),
  amount_released_minor integer not null default 0 check (amount_released_minor >= 0),
  currency text not null,
  allocation_reason_snapshot_json jsonb not null,
  allocation_status text not null,
  idempotency_key text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moral_goods_participant_donation_recipient_choices (
  id text primary key,
  lot_id text references public.moral_goods_crowdfunded_pledge_swap_lots(id),
  basket_item_id text references public.moral_goods_crowdfunded_pledge_swap_basket_items(id),
  participant_user_id uuid,
  approved_recipient_list_snapshot_hash text not null,
  selected_donation_recipient_id text not null references public.moral_goods_donation_recipients(id),
  fallback_donation_recipient_id text references public.moral_goods_donation_recipients(id),
  choice_status text not null,
  participant_terms_accepted_at timestamptz,
  chosen_at timestamptz,
  frozen_at timestamptz,
  replacement_reason_private text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moral_goods_sponsor_gap_fill_commitments (
  id text primary key,
  round_id text references public.moral_goods_group_buy_rounds(id),
  lot_id text references public.moral_goods_crowdfunded_pledge_swap_lots(id),
  basket_id text references public.moral_goods_crowdfunded_pledge_swap_baskets(id),
  sponsor_user_id uuid,
  trigger_threshold_bps integer not null check (trigger_threshold_bps >= 0 and trigger_threshold_bps <= 10000),
  trigger_threshold_amount_minor integer not null check (trigger_threshold_amount_minor >= 0),
  max_gap_fill_amount_minor integer not null check (max_gap_fill_amount_minor >= 0),
  amount_reserved_minor integer not null default 0 check (amount_reserved_minor >= 0),
  amount_used_minor integer not null default 0 check (amount_used_minor >= 0),
  currency text not null,
  eligible_scope_policy_snapshot_json jsonb not null,
  matching_rule_snapshot_json jsonb not null,
  reserve_status text not null,
  activation_status text not null,
  funding_deadline timestamptz not null,
  sponsor_terms_accepted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moral_goods_participant_pledge_swap_proposals (
  id text primary key,
  participant_user_id uuid,
  proposed_action_template_id text references public.moral_goods_action_templates(id),
  proposed_action_text_private text not null,
  proposed_consideration_type text not null,
  proposed_consideration_amount_minor integer check (proposed_consideration_amount_minor >= 0),
  currency text,
  proposed_donation_recipient_preferences_json jsonb,
  proposed_action_window_json jsonb,
  proposal_status text not null,
  safety_review_status text not null,
  methodology_review_status text not null,
  participant_welfare_review_status text not null,
  anti_threat_flags_json jsonb,
  converted_lot_id text references public.moral_goods_crowdfunded_pledge_swap_lots(id),
  converted_basket_id text references public.moral_goods_crowdfunded_pledge_swap_baskets(id),
  participant_visible_reason text,
  reviewer_notes_private text,
  submitted_at timestamptz,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moral_goods_team_activation_groups (
  id text primary key,
  round_id text references public.moral_goods_group_buy_rounds(id),
  group_type text not null,
  validity_mode text not null default 'team_threshold',
  initiator_user_id uuid,
  status text not null,
  activation_window_started_at timestamptz not null,
  activation_expires_at timestamptz not null,
  activated_at timestamptz,
  expired_at timestamptz,
  min_funder_count integer,
  min_participant_count integer,
  max_funder_count integer,
  max_participant_count integer,
  current_funder_count integer not null default 0,
  current_participant_count integer not null default 0,
  qualified_funder_count integer not null default 0,
  qualified_participant_count integer not null default 0,
  counts_recomputed_at timestamptz,
  counts_source_hash text,
  activation_lock_version integer not null default 1,
  public_group_id text unique,
  invite_token_hash text,
  invite_token_hash_policy_version text,
  invite_token_expires_at timestamptz,
  invite_max_uses integer,
  invite_use_count integer not null default 0,
  invite_status text not null default 'none',
  activation_effect text not null,
  capacity_reservation_status text not null default 'not_applicable',
  reserved_participant_slots integer,
  reserved_budget_minor integer,
  terms_snapshot_hash text not null,
  privacy_policy_snapshot_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (activation_window_started_at < activation_expires_at)
);

create table if not exists public.moral_goods_team_activation_members (
  id text primary key,
  activation_group_id text not null references public.moral_goods_team_activation_groups(id),
  user_id uuid,
  pledge_id text,
  enrollment_id text,
  invitation_id text,
  member_role text not null,
  status text not null,
  natural_person_dedup_status text not null,
  threshold_qualification_status text not null,
  joined_at timestamptz not null,
  activated_at timestamptz,
  expired_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (activation_group_id, user_id, member_role)
);

create table if not exists public.moral_goods_team_activation_invites (
  id text primary key,
  activation_group_id text not null references public.moral_goods_team_activation_groups(id),
  inviter_user_id uuid,
  invite_token_hash text not null unique,
  invite_token_hash_policy_version text not null,
  invite_status text not null,
  max_uses integer,
  use_count integer not null default 0,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  revoked_at timestamptz,
  abuse_report_count integer not null default 0,
  last_used_at timestamptz
);

create table if not exists public.moral_goods_funding_settlement_line_items (
  id text primary key,
  settlement_id text,
  purchase_envelope_type text not null,
  purchase_envelope_id text not null,
  funding_source_commitment_id text references public.moral_goods_funding_source_commitments(id),
  funding_source_type text not null,
  funding_source_id text not null,
  is_eligible_for_charge_or_use boolean not null,
  ineligible_reason text,
  amount_authorized_minor integer not null default 0 check (amount_authorized_minor >= 0),
  amount_reserved_minor integer not null default 0 check (amount_reserved_minor >= 0),
  amount_charged_or_used_minor integer not null default 0 check (amount_charged_or_used_minor >= 0),
  amount_released_minor integer not null default 0 check (amount_released_minor >= 0),
  rollover_amount_minor integer check (rollover_amount_minor >= 0),
  platform_fee_amount_minor integer check (platform_fee_amount_minor >= 0),
  provider_fee_amount_minor integer check (provider_fee_amount_minor >= 0),
  effective_cost_per_adjusted_unit_minor integer,
  funded_consideration_obligation_id text references public.moral_goods_consideration_obligations(id),
  funded_adjusted_units_milli bigint,
  currency text not null,
  calculation_input_hash text,
  calculation_output_hash text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (settlement_id, funding_source_commitment_id)
);

create table if not exists public.moral_goods_domain_event_outbox (
  id text primary key,
  aggregate_type text not null,
  aggregate_id text not null,
  purchase_envelope_type text,
  purchase_envelope_id text,
  event_type text not null,
  event_version text not null,
  event_payload_json_redacted jsonb,
  event_payload_hash text,
  redaction_policy_version text not null,
  idempotency_key text unique,
  occurred_at timestamptz not null default now(),
  available_for_dispatch_at timestamptz,
  dispatch_status text not null default 'pending',
  consumer_status_json_redacted jsonb,
  attempts integer not null default 0,
  last_error_redacted text,
  locked_by text,
  locked_at timestamptz,
  dispatched_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moral_goods_user_receipts (
  id text primary key,
  user_id uuid,
  round_id text references public.moral_goods_group_buy_rounds(id),
  entity_type text not null,
  entity_id text,
  receipt_type text not null,
  public_receipt_id text not null unique,
  receipt_snapshot_hash text not null,
  round_snapshot_hash text,
  receipt_json_redacted jsonb not null,
  created_at timestamptz not null default now(),
  delivered_at timestamptz,
  revoked_or_superseded_at timestamptz
);

create table if not exists public.moral_goods_ledger_transactions (
  id text primary key,
  transaction_type text not null,
  currency text not null,
  related_round_id text,
  related_settlement_id text,
  related_payment_operation_id text,
  idempotency_key text unique,
  memo_private text,
  created_by uuid,
  created_at timestamptz not null default now()
);

create table if not exists public.moral_goods_ledger_accounts (
  id text primary key,
  round_id text,
  owner_user_id uuid,
  account_type text not null,
  currency text not null,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moral_goods_ledger_entries (
  id text primary key,
  ledger_transaction_id text not null references public.moral_goods_ledger_transactions(id),
  account_id text not null references public.moral_goods_ledger_accounts(id),
  direction text not null check (direction in ('debit', 'credit')),
  amount_minor integer not null check (amount_minor >= 0),
  currency text not null,
  related_settlement_id text,
  related_payment_operation_id text,
  related_line_item_id text,
  memo_private text,
  created_at timestamptz not null default now()
);

create table if not exists public.moral_goods_payment_operations (
  id text primary key,
  settlement_id text,
  purchase_envelope_type text,
  purchase_envelope_id text,
  funding_source_commitment_id text references public.moral_goods_funding_source_commitments(id),
  consideration_obligation_id text references public.moral_goods_consideration_obligations(id),
  operation_type text not null check (operation_type in ('authorize', 'capture', 'release', 'payout', 'refund', 'rollover', 'charitable_donation')),
  amount_minor integer not null check (amount_minor >= 0),
  currency text not null,
  provider_name text not null,
  provider_operation_ref text,
  idempotency_key text unique,
  status text not null,
  last_error_redacted text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moral_goods_payment_provider_events (
  id text primary key,
  provider_name text not null,
  provider_event_id text not null unique,
  event_type text not null,
  provider_event_created_at timestamptz,
  signature_verification_status text not null,
  received_signature_hash text,
  payload_json_redacted jsonb not null,
  payload_hash text,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  processing_status text not null,
  related_payment_operation_id text references public.moral_goods_payment_operations(id),
  last_error_redacted text
);

create table if not exists public.moral_goods_settlements (
  id text primary key,
  purchase_envelope_type text not null,
  purchase_envelope_id text not null,
  settlement_scope text not null,
  purchase_envelope_snapshot_hash text not null,
  raw_units_total integer not null default 0,
  adjusted_units_total_milli bigint not null default 0,
  participant_payout_total_minor integer not null default 0,
  gross_participant_payout_total_minor integer,
  tax_withholding_total_minor integer,
  provider_fee_total_minor integer,
  sponsor_match_used_minor integer not null default 0,
  ordinary_funder_charge_total_minor integer not null default 0,
  refund_release_total_minor integer not null default 0,
  platform_fee_total_minor integer,
  currency text not null,
  settlement_status text not null,
  public_report_json jsonb not null,
  calculation_input_hash text not null,
  calculation_output_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moral_goods_participant_payouts (
  id text primary key,
  settlement_id text references public.moral_goods_settlements(id),
  participant_action_commitment_id text references public.moral_goods_participant_action_commitments(id),
  consideration_obligation_id text references public.moral_goods_consideration_obligations(id),
  raw_units_verified integer not null default 0,
  final_additionality_bps integer not null default 0,
  final_verification_confidence_bps integer not null default 0,
  final_moral_impact_weight_bps integer not null default 0,
  final_persistence_multiplier_bps integer not null default 0,
  adjusted_units_final_milli bigint not null default 0,
  payout_amount_minor integer not null default 0,
  gross_payout_amount_minor integer,
  tax_withholding_amount_minor integer,
  provider_fee_amount_minor integer,
  platform_fee_amount_minor integer,
  rounding_delta_minor integer,
  currency text not null,
  payout_destination_ref_snapshot text,
  payout_destination_verified_at timestamptz,
  payout_retry_after timestamptz,
  payout_expires_at timestamptz,
  payout_failure_reason_redacted text,
  unclaimed_property_status text,
  payout_status text not null,
  payout_provider_ref text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moral_goods_audit_events (
  id text primary key,
  actor_user_id uuid,
  entity_type text not null,
  entity_id text not null,
  action text not null,
  before_json_redacted jsonb,
  after_json_redacted jsonb,
  before_hash text,
  after_hash text,
  redaction_policy_version text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.moral_goods_disputes (
  id text primary key,
  round_id text,
  purchase_envelope_type text,
  purchase_envelope_id text,
  participant_action_commitment_id text references public.moral_goods_participant_action_commitments(id),
  funding_source_commitment_id text references public.moral_goods_funding_source_commitments(id),
  consideration_obligation_id text references public.moral_goods_consideration_obligations(id),
  opened_by uuid,
  dispute_type text not null,
  status text not null,
  blocks_settlement boolean not null default true,
  claim_text_private text not null,
  participant_visible_summary text,
  resolution_text_private text,
  public_resolution text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moral_goods_verification_submissions (
  id text primary key,
  participant_action_commitment_id text references public.moral_goods_participant_action_commitments(id),
  submitted_by uuid,
  submission_type text not null,
  evidence_metadata_json jsonb not null,
  private_evidence_storage_ref text,
  evidence_mime_type text,
  evidence_size_bytes integer,
  evidence_scan_status text not null,
  evidence_original_hash text,
  evidence_sanitized_preview_hash text,
  evidence_redacted_derivative_hash text,
  evidence_processing_policy_version text,
  evidence_metadata_stripped_at timestamptz,
  third_party_redaction_status text,
  evidence_retention_expires_at timestamptz,
  public_summary text,
  submitted_at timestamptz not null default now()
);

create table if not exists public.moral_goods_verification_decisions (
  id text primary key,
  participant_action_commitment_id text references public.moral_goods_participant_action_commitments(id),
  reviewer_user_id uuid,
  raw_units_verified integer not null default 0,
  compliance_status text not null,
  verification_confidence_bps integer not null default 0,
  reviewer_notes_private text,
  participant_visible_reason text,
  participant_visible_at timestamptz,
  dispute_deadline_at timestamptz,
  decided_at timestamptz not null default now()
);

create table if not exists public.moral_goods_evidence_access_logs (
  id text primary key,
  submission_id text not null references public.moral_goods_verification_submissions(id),
  viewer_user_id uuid,
  access_reason text not null,
  action text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.moral_goods_risk_reviews (
  id text primary key,
  entity_type text not null,
  entity_id text not null,
  risk_type text not null,
  reviewer_user_id uuid,
  status text not null,
  rationale_private text not null,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.moral_goods_review_quality_audits (
  id text primary key,
  entity_type text not null,
  entity_id text not null,
  review_type text not null,
  original_reviewer_user_id uuid,
  audit_reviewer_user_id uuid,
  blinding_applied boolean not null default false,
  outcome text not null,
  notes_private text,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.moral_goods_ai_processing_logs (
  id text primary key,
  entity_type text not null,
  entity_id text not null,
  processor_name text not null,
  processor_type text not null,
  purpose text not null,
  input_redaction_policy_version text not null,
  prompt_or_request_hash text,
  output_ref text,
  output_hash text,
  human_review_required boolean not null default true,
  status text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.moral_goods_mutation_idempotency_records (
  id text primary key,
  actor_user_id uuid,
  operation_type text not null,
  scope_entity_type text,
  scope_entity_id text,
  idempotency_key text not null unique,
  request_hash text not null,
  response_entity_type text,
  response_entity_id text,
  status text not null,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moral_goods_terms_acceptances (
  id text primary key,
  user_id uuid,
  round_id text,
  entity_type text not null,
  entity_id text,
  terms_type text not null,
  round_snapshot_hash text,
  terms_snapshot_hash text not null,
  accepted_version text not null,
  request_context_hash_redacted text,
  accepted_at timestamptz not null default now(),
  revoked_at timestamptz,
  revocation_reason_private text,
  superseding_terms_acceptance_id text references public.moral_goods_terms_acceptances(id)
);

create table if not exists public.moral_goods_operational_pauses (
  id text primary key,
  scope text not null,
  round_id text,
  status text not null,
  pause_type text not null,
  reason_private text not null,
  public_message text,
  created_by uuid,
  lifted_by uuid,
  created_at timestamptz not null default now(),
  lifted_at timestamptz
);

create table if not exists public.moral_goods_incident_reports (
  id text primary key,
  round_id text,
  incident_type text not null,
  severity text not null,
  status text not null,
  opened_by uuid,
  owner_user_id uuid,
  private_summary text not null,
  public_message text,
  containment_action_private text,
  linked_operational_pause_id text references public.moral_goods_operational_pauses(id),
  postmortem_private text,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.moral_goods_deadline_jobs (
  id text primary key,
  round_id text,
  job_type text not null,
  scheduled_for timestamptz not null,
  idempotency_key text not null unique,
  status text not null,
  attempts integer not null default 0,
  last_error_redacted text,
  locked_by text,
  locked_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moral_goods_privacy_erasure_requests (
  id text primary key,
  requester_user_id uuid,
  subject_user_id uuid,
  scope text not null,
  status text not null,
  legal_hold_reason text,
  public_status_summary text,
  private_notes text,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.moral_goods_data_retention_actions (
  id text primary key,
  round_id text,
  related_erasure_request_id text references public.moral_goods_privacy_erasure_requests(id),
  entity_type text not null,
  entity_id text not null,
  action_type text not null,
  status text not null,
  before_hash text,
  after_tombstone_hash text,
  executed_by uuid,
  executed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.moral_goods_data_backfill_jobs (
  id text primary key,
  job_type text not null,
  source_feature text not null,
  target_entity_type text not null,
  status text not null,
  dry_run_counts_json_redacted jsonb,
  reconciliation_summary_json_redacted jsonb,
  reconciliation_hash text,
  idempotency_key text unique,
  started_at timestamptz,
  completed_at timestamptz,
  last_error_redacted text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moral_goods_reconciliation_runs (
  id text primary key,
  round_id text,
  reconciliation_type text not null,
  status text not null,
  input_hash text,
  result_summary_json_redacted jsonb,
  discrepancy_count integer,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moral_goods_backup_restore_checks (
  id text primary key,
  scope text not null,
  environment text not null,
  status text not null,
  backup_taken_at timestamptz,
  restore_tested_at timestamptz,
  result_summary_json_redacted jsonb,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists moral_goods_registry_state_idx
  on public.moral_goods_purchase_envelope_registry (lifecycle_state_group, envelope_type);

create index if not exists moral_goods_funding_sources_envelope_idx
  on public.moral_goods_funding_source_commitments (purchase_envelope_type, purchase_envelope_id, funding_source_status);

create index if not exists moral_goods_action_commitments_envelope_idx
  on public.moral_goods_participant_action_commitments (purchase_envelope_type, purchase_envelope_id, commitment_status);

create index if not exists moral_goods_outbox_dispatch_idx
  on public.moral_goods_domain_event_outbox (dispatch_status, available_for_dispatch_at);

create index if not exists moral_goods_deadline_jobs_due_idx
  on public.moral_goods_deadline_jobs (status, scheduled_for);
